name: Connect to MySQL database

on:
  push:
    branches:
      - main

jobs:
  connect-to-mysql:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Connect to MySQL database
        uses: mysql-actions/mysql@v0.1.0
        with:
          host: 127.0.0.1
          user: ${{ secrets.SQL_Configuration.username }}
          password: ${{ secrets.SQL_Configuration.password }}
          database: ${{ secrets.SQL_Configuration.database }}

      - name: Perform query
        run: |
          mysql --host 127.0.0.1 -u ${{ secrets.SQL_Configuration.username }} -p ${{ secrets.SQL_Configuration.password }} ${{ secrets.SQL_Configuration.database }} -e "SELECT * FROM Student"
